const values = {
    "_realiz_ejercicio_":true,
    "alimentacin":{
       "Alta en carbohidratos":{
          "checked":null,
          "textarea":""
       },
       "Alta en sodio":{
          "checked":null,
          "textarea":""
       },
       "Dieta":{
          "checked":null,
          "textarea":""
       },
       "Habitual":{
          "checked":true,
          "textarea":""
       }
    },
    "cumpli_hoy_con_tto":true,
    "diastlica":"68",
    "especificar":"",
    "peso":"",
    "presin":"",
    "pulso":"70",
    "sistlica":"110",
    "sntomas_agregados":{
       "Dolor de brazo":{
          "checked":null,
          "textarea":""
       },
       "Dolor de cabeza":{
          "checked":null,
          "textarea":""
       },
       "Mareos":{
          "checked":null,
          "textarea":""
       },
       "Ninguno":{
          "checked":true,
          "textarea":""
       }
    },
    "tiempo_de_realizar_el_ejercicio":"30 min.",
    "tipo_de_ejercicio":{
       "Bicicleta":{
          "checked":null,
          "textarea":""
       },
       "Caminar":{
          "checked":null,
          "textarea":""
       },
       "Correr":{
          "checked":null,
          "textarea":""
       },
       "Gimnasio":{
          "checked":null,
          "textarea":""
       },
       "Natación":{
          "checked":null,
          "textarea":""
       },
       "Otro":{
          "checked":null,
          "textarea":""
       },
       "Trotar":{
          "checked":true,
          "textarea":""
       }
    }
 }